### PR TITLE
Julia in docker image

### PR DESCRIPTION
**Pull request by simone-silvestri**
Attempt to add Julia in the coessing image

### CODE REVIEW

**Comment by simone-silvestri** [comment]
@sgibson91 Is this ok to merge then? How can I test the image?

**Comment by sgibson91** [comment]
Unfortunately, Pangeo Binder (on GCP) is down so we can't use that for testing. We could test it on mybinder.org?, just the dask-stuff won't work: https://mybinder.org/v2/gh/2i2c-org/coessing-image/ss/julia_in_dockerimage

**Comment by sgibson91** [comment]
Screenshot 2022-07-25 at 16 14 24

Yay! 🎉 I think you are good to merge!

**Comment by simone-silvestri** [comment]
Seems like julia has been correctly added. Thanks for the help @sgibson91, I will merge

**Pull request merged**
